baseURL = "https://hogexcom.github.io/my-site/"
languageCode = 'ja-JP'
title = 'My Site'
theme = "PaperMod"

[params]
  math = true

[outputs]
  home = [ "HTML" ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true